apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: samjna-services/analytics:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
          env:
          - name: PORT
            value: "8001"
          - name: API_URL
            valueFrom:
              secretKeyRef:
                name: secrets
                key: core-api-url
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: secrets
                key: core-api-key
          - name: GEMINI_API_KEY
            valueFrom:
              secretKeyRef:
                name: secrets
                key: gemini-api-key
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "6Gi"
              cpu: "2"
          livenessProbe:
            httpGet:
              path: /analytics-service/health
              port: 8001
            initialDelaySeconds: 300
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /analytics-service/health
              port: 8001
            initialDelaySeconds: 300
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: analytics
spec:
  selector:
    app: analytics
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: analytics-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: analytics
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70